apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::275839157288:role/todo-staging-node-role
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2026-09-28T17:15:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "7418"
  uid: a91d4b9e-b33c-4d6a-b541-151e8f8cf12b
