apiVersion: v1
kind: Pod
metadata:
  name: karpenter-test
spec:
  nodeSelector:
    karpenter.sh/nodepool: default

  containers:
    - name: nginx
      image: public.ecr.aws/docker/library/nginx:latest
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
